M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Tue 26 Mar 2024 10:14:37 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-26T10:14:37-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X3.128Y-4.4413
X3.128Y-4.6146
T0
M30
